osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AppStoreInformation.xcworkspace -scheme AppStoreInformation-Example -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
